apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-api
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: tracking-api
  template: 
    metadata:
      labels:
        app: tracking-api
    spec:
      containers:
      - name: tracking-api
        image: acrtrackingservice.azurecr.io/tracking-svc-api:20190601.1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: KeyVault__Endpoint
            value: <KeyVaultEndpoint>
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: tracking-api
  labels: 
    apps: tracking-api
spec:
  selector:
    app: tracking-api
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
