resources:
- repo: self
name: $(date:yyyy).1.0$(rev:.rrr)
queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'


- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-Task@1
  displayName: 'Set Assembly Manifest Data'
  inputs:
    FileNames: '*.csproj'
    InsertAttributes: true
    Title: 'Tracking api '
    Description: 'Simple api to test out the Azure dev-ops capabilities'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True


- task: PublishBuildArtifacts@1
  displayName: 'Publish Web Artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/TrackerService.Api.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Sql Scripts'
  inputs:
    PathtoPublish: 'TrackerService.Data/SqlFiles'

- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM Artifacts'
  inputs:
    PathtoPublish: TrackerService.Deployment
    ArtifactName: arm
