apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: tracking-svc-api 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tracking-svc-api 
    spec:
      containers:
        - name: tracking-svc-api 
          image: trackingservice.azurecr.io/tracking-svc-api 
          ports:
          - containerPort: 80
          env:
            - name: KeyVault__SPClientId
              value: #{keyvault.clientId}#
            - name: KeyVault__SPClientSecret
              value: #{keyvault.clientSecret}#